# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QTiTC2TY1CjE0Jey8WHjnFIV98sQSvdfZEOXzIrLFU9G2ESl6OLByyrvFi3qRdeuhW3iQUThBl6VeeWEZHlXWKNJOuHhMTfNJw2hYIfLnUie1RO2asKXn0m0AHLP7l8AL2zmW5QPHghDTzY4ry/WUVyuUNbYWpVLeS7/5ffkXKrIrgOPMmzssIsIj48B7bQfreN4xF+pEawumuLhdgSi84YKE7De1b7KsIAnqSOeicYpPjcaWzajMPzxwpPz0OAcY8vspLDhEHKJZUBGzkHvGvj+kg1gXtacgS/3D6nUD8joUcv+JpozQS7SXJfhcwqK6k/XVaj1HLKVWVvHPt4A8063U8oRZomAB6UGoUhQ1SyiTEl6XAOHHDn192Oe6aE2nb8CuIEMDK+hbgF6nskdC6bQBMDWVITMr8Q7XHFnedW8YW/ZC6ejR2onzKNkBxe/nXH8kEXxe5ef4YqioMjIGEeEuwmoZvqlk14FQuD0br6Bmh9tkYsRRn7lwgkwc1hd/nHAEhr3UUSJeAI8q05dmxUa/s3+c7t9tzp+zL6CG5pcnABkx1F+jgjDXZFa1U7ZwnR+wNlZp02b/RvtTYvxWTSx/+Qn6rier7tuMOvie71RABnry1fMZnlfs9fbqnmrygEVwWvQw/4jOQkV4J4FSKnuMER0MeUuABSLsj8fUus="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
